name: ci

on: push

env:
  DEBIAN_FRONTEND: noninteractive

jobs:
  run:
    runs-on: ubuntu-20.04
    # container:
    #   image: ubuntu:20.04
    steps:
      - uses: actions/checkout@v2

      - name: Check builder
        run: |
          lscpu
          free -h 
          df -h

      - name: Setup
        run: |
          bash scripts/install_pkgs.sh

      - name: Test
        run: |
          bash scripts/test.sh

      - uses: iterative/setup-cml@v1
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # cat /tmp/free_output.txt >> report.md
          bash scripts/plot.sh

          cml publish mem_info.png >> report.md
          cml send-comment report.md
